import pytest
import jax.numpy as jnp
import numpyro.distributions as dist
from numpyro.handlers import trace, substitute, seed
from collections import namedtuple

# --- Import Module Under Test (MUT) ---
from tfscreen.analysis.hierarchical.growth_model.components.theta_hill import (
    ModelPriors,
    ThetaParam,
    define_model,
    guide,
    run_model,
    get_hyperparameters,
    get_guesses,
    get_priors
)

# --- Mock Data Fixture ---

MockDataClass = namedtuple("MockDataClass", [
    "num_titrant_name",
    "num_titrant_conc",
    "num_genotype",
    "batch_size",
    "batch_idx",
    "scale_vector",
    "log_titrant_conc",
    "geno_theta_idx",
    "scatter_theta"
])

@pytest.fixture
def mock_data():
    """
    Provides a mock data object for testing.
    """
    num_titrant_name = 2
    num_titrant_conc = 3
    num_genotype = 3
    
    batch_size = 3
    batch_idx = jnp.arange(batch_size, dtype=jnp.int32)
    scale_vector = jnp.ones(batch_size, dtype=float)
    
    log_titrant_conc = jnp.linspace(-5, 5, num_titrant_conc)
    geno_theta_idx = jnp.arange(num_genotype, dtype=jnp.int32)
    
    return MockDataClass(
        num_titrant_name=num_titrant_name,
        num_titrant_conc=num_titrant_conc,
        num_genotype=num_genotype,
        batch_size=batch_size,
        batch_idx=batch_idx,
        scale_vector=scale_vector,
        log_titrant_conc=log_titrant_conc,
        geno_theta_idx=geno_theta_idx,
        scatter_theta=1
    )

@pytest.fixture
def theta_param_setup(mock_data):
    """
    Returns a ThetaParam object generated by running define_model.
    """
    name = "test_hill"
    priors = get_priors()
    
    base_guesses = get_guesses(name, mock_data)
    batch_guesses = base_guesses.copy()
    
    for k in batch_guesses:
        if "offset" in k:
            batch_guesses[k] = batch_guesses[k][..., mock_data.batch_idx]

    substituted_model = substitute(define_model, data=batch_guesses)
    theta_param = substituted_model(name=name,
                                    data=mock_data,
                                    priors=priors)
    return theta_param

# --- Test Cases ---

def test_get_hyperparameters():
    """Tests that get_hyperparameters returns the correct structure."""
    params = get_hyperparameters()
    assert isinstance(params, dict)
    assert "theta_logit_low_hyper_loc_loc" in params

def test_get_priors():
    """Tests that get_priors returns a correctly populated ModelPriors object."""
    priors = get_priors()
    assert isinstance(priors, ModelPriors)

def test_get_guesses(mock_data):
    """Tests that get_guesses returns correctly named and shaped guesses."""
    name = "test_hill"
    guesses = get_guesses(name, mock_data)
    assert isinstance(guesses, dict)
    expected_shape = (mock_data.num_titrant_name, mock_data.num_genotype)
    assert guesses[f"{name}_logit_low_offset"].shape == expected_shape

def test_define_model_shapes_and_values(mock_data):
    """
    Tests define_model output shapes and values using zero-offset guesses.
    """
    name = "test_hill"
    priors = get_priors()
    
    base_guesses = get_guesses(name, mock_data)
    batch_guesses = base_guesses.copy()
    for k in batch_guesses:
        if "offset" in k:
            batch_guesses[k] = batch_guesses[k][..., mock_data.batch_idx]

    substituted_model = substitute(define_model, data=batch_guesses)
    
    theta_param = substituted_model(name=name,
                                    data=mock_data,
                                    priors=priors)
    
    expected_shape = (mock_data.num_titrant_name, mock_data.batch_size)
    assert theta_param.theta_low.shape == expected_shape
    assert theta_param.log_hill_K.shape == expected_shape
    assert theta_param.mu.shape == (1, mock_data.num_titrant_conc, 1) or theta_param.mu.shape == (mock_data.num_titrant_name, mock_data.num_titrant_conc, 1)

def test_run_model_calculation(mock_data):
    """
    Strict calculation test.
    """
    shape = (mock_data.num_titrant_name, mock_data.num_genotype)
    
    theta_low = jnp.zeros(shape)
    theta_high = jnp.ones(shape)
    log_hill_K = jnp.zeros(shape)
    hill_n = jnp.ones(shape)
    mu_pop = jnp.zeros((mock_data.num_titrant_name, mock_data.num_titrant_conc, 1))
    sigma_pop = jnp.ones((mock_data.num_titrant_name, mock_data.num_titrant_conc, 1))
    
    theta_param = ThetaParam(theta_low, theta_high, log_hill_K, hill_n, mu_pop, sigma_pop)

    new_concs = jnp.array([-10.0, 0.0, 10.0])
    mock_data = mock_data._replace(log_titrant_conc=new_concs, scatter_theta=0)
    
    result = run_model(theta_param, mock_data)
    
    assert jnp.allclose(result[:, 0, :], 0.0, atol=1e-3)
    assert jnp.allclose(result[:, 1, :], 0.5)
    assert jnp.allclose(result[:, 2, :], 1.0, atol=1e-3)

def test_run_model_scatter(theta_param_setup, mock_data):
    """
    Test that the scatter functionality reshapes the output correctly.
    """
    theta_param = theta_param_setup
    data = mock_data._replace(scatter_theta=1)
    result = run_model(theta_param, data)
    
    expected_shape = (1, 1, 1, 1, 
                      mock_data.num_titrant_name, 
                      mock_data.num_titrant_conc, 
                      mock_data.batch_size)
    assert result.shape == expected_shape

def test_guide_logic_and_shapes(mock_data):
    """
    Tests the guide function shapes, parameter creation, and execution.
    """
    name = "test_hill_guide"
    priors = get_priors()

    with seed(rng_seed=0):
        guide_trace = trace(guide).get_trace(
            name=name,
            data=mock_data,
            priors=priors
        )
        theta_param = guide(name=name,
                            data=mock_data,
                            priors=priors)

    expected_batch_shape = (mock_data.num_titrant_name, mock_data.batch_size)
    assert theta_param.theta_low.shape == expected_batch_shape
    assert theta_param.mu.shape == (1, mock_data.num_titrant_conc, 1)

def test_population_moments_logic(mock_data):
    """
    Verify that get_population_moments returns the expected tensors.
    """
    name = "test_moments"
    priors = get_priors()
    
    with seed(rng_seed=0):
        theta_param = define_model(name, mock_data, priors)
        
    from tfscreen.analysis.hierarchical.growth_model.components.theta_hill import get_population_moments
    mu, sigma = get_population_moments(theta_param, mock_data)
    
    # Expected shape (1, Conc, 1) because hyper-params are global
    assert mu.shape == (1, mock_data.num_titrant_conc, 1)
    assert sigma.shape == (1, mock_data.num_titrant_conc, 1)
    assert jnp.all(sigma > 0)