import os
import yaml
import pandas as pd
import numpy as np
import jax.numpy as jnp
from flax import struct

from tfscreen.analysis.hierarchical.growth_model import GrowthModel
from tfscreen.analysis.hierarchical.run_inference import RunInference
from tfscreen.util.cli.generalized_main import generalized_main
from tfscreen.analysis.hierarchical.analyze_theta import _run_svi, _run_map

def update_dataclass(dc, prefix, flat_dict):
    import dataclasses
    updates = {}
    
    # Check if this is a standard dataclass or a flax struct dataclass
    if hasattr(dc, '__dataclass_fields__'):
        fields = dataclasses.fields(dc) if dataclasses.is_dataclass(dc) else dc.__dataclass_fields__.values()
        
        for field in fields:
            field_name = field.name
            full_key = f"{prefix}{field_name}" if prefix else field_name
            attr_val = getattr(dc, field_name)
            
            if hasattr(attr_val, '__dataclass_fields__'):
                updates[field_name] = update_dataclass(attr_val, full_key + ".", flat_dict)
            elif full_key in flat_dict:
                updates[field_name] = flat_dict[full_key]
                
        if len(updates) > 0:
            if hasattr(dc, "replace"):
                return dc.replace(**updates)
            else:
                return dataclasses.replace(dc, **updates)
    return dc

def run_growth_analysis(config_file,
                        guesses_file=None,
                        seed=None,
                        checkpoint_file=None,
                        analysis_method="svi",
                        out_root="tfs",
                        adam_step_size=1e-3,
                        adam_final_step_size=1e-6,
                        adam_clip_norm=1.0,
                        elbo_num_particles=2,
                        convergence_tolerance=0.01,
                        convergence_window=10,
                        patience=10,
                        convergence_check_interval=2,
                        checkpoint_interval=10,
                        max_num_epochs=100000,
                        num_posterior_samples=10000,
                        sampling_batch_size=100,
                        forward_batch_size=512,
                        always_get_posterior=False,
                        pre_map_num_epoch=1000,
                        init_param_jitter=0.1):
    """
    Run the joint hierarchical growth model using a previously generated configuration file.

    This function extracts estimates of transcription factor fractional occupancy (theta) 
    and other latent parameters using Stochastic Variational Inference (SVI) or maximum a
    posteriori (MAP) approaches based on the config.

    Parameters
    ----------
    config_file : str
        Path to a YAML configuration file to load settings from.
    guesses_file : str, optional
        Path to a CSV file containing initial array parameter guesses, typically 
        generated by configure_growth_analysis.
    seed : int, optional
        Random seed for reproducibility. Must be provided if not loading from a checkpoint.
    checkpoint_file : str or None, optional
        Path to a checkpoint file to resume SVI from, or None to start fresh.
    analysis_method : str, optional
        Method for inference. Allowed values are 'svi' (default), 'map', or 
        'posterior'.
    out_root : str, optional
        Output file root for checkpoints and results (default 'tfs').
    adam_step_size : float, optional
        Starting step size for the Adam optimizer (default 1e-3).
    adam_final_step_size : float, optional
        Final step size for the Adam optimizer (default 1e-6).
    adam_clip_norm : float, optional
        Gradient clipping norm for Adam optimizer (default 1.0).
    elbo_num_particles : int, optional
        Number of particles for ELBO estimation (default 2).
    convergence_tolerance : float, optional
        Relative change in loss to declare SVI convergence (default 0.01).
    convergence_window : int, optional
        Number of epochs to average for convergence check (default 10).
    patience : int, optional
        Number of consecutive checks meeting tolerance to declare convergence
        (default 10).
    convergence_check_interval : int, optional
        Frequency (in epochs) to check for convergence (default 2).
    checkpoint_interval : int, optional
        Frequency (in epochs) between checkpoints (default 10).
    max_num_epochs : int, optional
        Maximum number of SVI optimization epochs (default 100000).
    num_posterior_samples : int, optional
        Number of posterior samples to draw after convergence (default 10000).
    sampling_batch_size : int, optional
        When getting posteriors, sample parameter posteriors in batches of this
        size (default 100).
    forward_batch_size : int, optional
        When getting posteriors, calculate forward predictions in batches of
        this size (default 512).
    always_get_posterior : bool, optional
        If True, always generate and save posterior samples, even if the
        optimization did not formally converge (default False).
    pre_map_num_epoch : int, optional
        Number of MAP iterations to run prior to SVI (default 1000). Only used
        if analysis_method is 'svi'. 
    init_param_jitter : float, optional
        Amount of jitter to add after the (optional) MAP run to break symmetry
        (default 0.1).

    Returns
    -------
    svi_state : Any
        Final SVI state object from the optimizer.
    svi_params : dict
        Final optimized parameters from SVI.
    converged : bool
        True if SVI converged according to the specified tolerance.
    """

    if seed is None and checkpoint_file is None:
        raise ValueError("seed must be provided unless loading from a checkpoint.")

    if not os.path.exists(config_file):
        raise FileNotFoundError(f"Configuration file not found: {config_file}")

    with open(config_file, "r") as f:
        config = yaml.safe_load(f)

    # 1. Initialize GrowthModel with components from config
    growth_df_path = config["data"]["growth"]
    binding_df_path = config["data"]["binding"]
    components = config["components"]
    
    batch_size = components.pop("batch_size", None)

    gm = GrowthModel(growth_df_path,
                     binding_df_path,
                     batch_size=batch_size,
                     **components)

    # 2. Update Priors
    new_priors = update_dataclass(gm.priors, "", config.get("priors", {}))
    # Python allows us to overwrite the property's underlying storage
    gm._priors = new_priors

    # 3. Construct init_params
    base_init_params = config.get("init_params", {})
    init_params = {}
    
    # Load scalar guesses
    for k, v in gm.init_params.items():
        if not hasattr(v, 'shape') or len(v.shape) == 0:
            init_params[k] = base_init_params.get(k, float(v))

    # Load array guesses from existing arrays or from CSV overrides
    array_guesses = {}
    if guesses_file is not None and os.path.exists(guesses_file):
        guesses_df = pd.read_csv(guesses_file)
        # Groups parameter flat array
        for param_name, df_group in guesses_df.groupby("parameter"):
            sorted_group = df_group.sort_values("flat_index")
            val_array = sorted_group["value"].values
            
            # Look up original shape
            if param_name in gm.init_params:
                orig_shape = gm.init_params[param_name].shape
                array_guesses[param_name] = jnp.array(val_array.reshape(orig_shape))
                
    # Fill in any missing array guesses with original guesses
    for k, v in gm.init_params.items():
        if hasattr(v, 'shape') and len(v.shape) > 0:
            if k in array_guesses:
                init_params[k] = array_guesses[k]
            else:
                init_params[k] = v
                
    # 4. Run SVI / MAP
    ri = RunInference(gm, seed)

    if analysis_method == "svi":
        if pre_map_num_epoch > 0 and checkpoint_file is None:
            _, init_params, _ = _run_map(ri,
                                         init_params=init_params,
                                         checkpoint_file=None,
                                         out_root=f"{out_root}_premap",
                                         adam_step_size=adam_step_size,
                                         adam_final_step_size=adam_final_step_size,
                                         adam_clip_norm=adam_clip_norm,
                                         elbo_num_particles=elbo_num_particles,
                                         checkpoint_interval=pre_map_num_epoch,
                                         max_num_epochs=pre_map_num_epoch,
                                         init_param_jitter=0.0)

        return _run_svi(ri,
                        init_params=init_params,
                        checkpoint_file=checkpoint_file,
                        out_root=out_root,
                        adam_step_size=adam_step_size,
                        adam_final_step_size=adam_final_step_size,
                        adam_clip_norm=adam_clip_norm,
                        elbo_num_particles=elbo_num_particles,
                        convergence_tolerance=convergence_tolerance,
                        convergence_window=convergence_window,
                        patience=patience,
                        convergence_check_interval=convergence_check_interval,
                        checkpoint_interval=checkpoint_interval,
                        max_num_epochs=max_num_epochs,
                        num_posterior_samples=num_posterior_samples,
                        sampling_batch_size=sampling_batch_size,
                        forward_batch_size=forward_batch_size,
                        always_get_posterior=always_get_posterior,
                        init_param_jitter=init_param_jitter)
    
    elif analysis_method == "map":
        return _run_map(ri,
                        init_params=init_params,
                        checkpoint_file=checkpoint_file,
                        out_root=out_root,
                        adam_step_size=adam_step_size,
                        adam_final_step_size=adam_final_step_size,
                        adam_clip_norm=adam_clip_norm,
                        elbo_num_particles=elbo_num_particles,
                        convergence_tolerance=convergence_tolerance,
                        convergence_window=convergence_window,
                        patience=patience,
                        convergence_check_interval=convergence_check_interval,
                        checkpoint_interval=checkpoint_interval,
                        max_num_epochs=max_num_epochs,
                        num_posterior_samples=num_posterior_samples,
                        sampling_batch_size=sampling_batch_size,
                        forward_batch_size=forward_batch_size,
                        always_get_posterior=always_get_posterior,
                        init_param_jitter=init_param_jitter)
                          
    elif analysis_method == "posterior":
        return _run_svi(ri,
                        init_params=init_params,  # Use our constructed init_params instead of None 
                        checkpoint_file=checkpoint_file,
                        out_root=out_root,
                        adam_step_size=adam_step_size,
                        adam_final_step_size=adam_final_step_size,
                        adam_clip_norm=adam_clip_norm,
                        elbo_num_particles=elbo_num_particles,
                        convergence_tolerance=convergence_tolerance,
                        convergence_window=convergence_window,
                        patience=patience,
                        convergence_check_interval=convergence_check_interval,
                        checkpoint_interval=checkpoint_interval,
                        max_num_epochs=0, 
                        num_posterior_samples=num_posterior_samples,
                        sampling_batch_size=sampling_batch_size,
                        forward_batch_size=forward_batch_size,
                        always_get_posterior=True, 
                        init_param_jitter=0.0)

    else:
        raise ValueError(
            f"analysis method '{analysis_method}' not recognized. This should "
            "be 'svi', 'map', or 'posterior'"
        )

def main():
    return generalized_main(run_growth_analysis,
                            manual_arg_types={"config_file":str,
                                              "guesses_file":str,
                                              "seed":int,
                                              "checkpoint_file":str,
                                              "pre_map_num_epoch":int,
                                              "init_param_jitter":float})

if __name__ == "__main__":
    main()
