import pytest
import numpy as np
import jax.numpy as jnp
import numpyro.distributions as dist
from numpyro.handlers import trace, substitute, seed
from collections import namedtuple

# --- Import Module Under Test (MUT) ---
from tfscreen.analysis.hierarchical.growth_model.components.theta.hill import (
    ModelPriors,
    ThetaParam,
    define_model,
    guide,
    run_model,
    get_population_moments,
    get_hyperparameters,
    get_guesses,
    get_priors,
    _population_moments,
)

# --- Mock Data Fixture ---

MockDataClass = namedtuple("MockDataClass", [
    "num_titrant_name",
    "num_titrant_conc",
    "num_genotype",
    "batch_size",
    "batch_idx",
    "scale_vector",
    "log_titrant_conc",
    "geno_theta_idx",
    "scatter_theta",
])

@pytest.fixture
def mock_data():
    num_titrant_name = 2
    num_titrant_conc = 3
    num_genotype = 3

    batch_size = 3
    batch_idx = jnp.arange(batch_size, dtype=jnp.int32)
    scale_vector = jnp.ones(batch_size, dtype=float)

    log_titrant_conc = jnp.linspace(-5, 5, num_titrant_conc)
    geno_theta_idx = jnp.arange(num_genotype, dtype=jnp.int32)

    return MockDataClass(
        num_titrant_name=num_titrant_name,
        num_titrant_conc=num_titrant_conc,
        num_genotype=num_genotype,
        batch_size=batch_size,
        batch_idx=batch_idx,
        scale_vector=scale_vector,
        log_titrant_conc=log_titrant_conc,
        geno_theta_idx=geno_theta_idx,
        scatter_theta=1,
    )


@pytest.fixture
def theta_param_setup(mock_data):
    """
    Returns a ThetaParam object generated by running define_model with zero
    offsets.  ThetaParam fields are shaped (T, G) — the full population.
    """
    name = "test_hill"
    priors = get_priors()
    guesses = get_guesses(name, mock_data)

    substituted_model = substitute(define_model, data=guesses)
    theta_param = substituted_model(name=name, data=mock_data, priors=priors)
    return theta_param


# ---------------------------------------------------------------------------
# get_hyperparameters / get_priors / get_guesses
# ---------------------------------------------------------------------------

def test_get_hyperparameters():
    params = get_hyperparameters()
    assert isinstance(params, dict)
    assert "theta_logit_low_hyper_loc_loc" in params


def test_get_priors():
    priors = get_priors()
    assert isinstance(priors, ModelPriors)


def test_get_guesses(mock_data):
    name = "test_hill"
    guesses = get_guesses(name, mock_data)
    assert isinstance(guesses, dict)
    T, G = mock_data.num_titrant_name, mock_data.num_genotype
    assert guesses[f"{name}_logit_low_offset"].shape == (T, G)
    # Hyperprior guesses are per-titrant vectors, not scalars
    assert guesses[f"{name}_logit_low_hyper_loc"].shape == (T,)
    assert guesses[f"{name}_log_hill_K_hyper_loc"].shape == (T,)


def test_get_guesses_log_hill_K_from_median(mock_data):
    """log_hill_K_hyper_loc is the median of finite log_titrant_conc values,
    broadcast to shape (T,)."""
    name = "th"
    # mock_data has log_titrant_conc = linspace(-5, 5, 3) = [-5, 0, 5]
    # median of all-finite values = 0.0
    guesses = get_guesses(name, mock_data)
    assert jnp.allclose(guesses[f"{name}_log_hill_K_hyper_loc"], 0.0, atol=1e-5)


def test_get_guesses_excludes_neg_inf():
    """Zero concentrations (stored as -inf in log) are excluded from median."""
    MockSimple = namedtuple("MockSimple", [
        "num_titrant_name", "num_genotype", "log_titrant_conc"
    ])
    data = MockSimple(
        num_titrant_name=1,
        num_genotype=2,
        log_titrant_conc=jnp.array([-np.inf, -3.0, -1.0]),
    )
    guesses = get_guesses("th", data)
    # finite values: [-3, -1], median = -2.0
    assert jnp.allclose(guesses["th_log_hill_K_hyper_loc"], -2.0, atol=1e-5)


def test_get_guesses_fallback_all_neg_inf():
    """All-inf log concentrations trigger the hard-coded -4.1 fallback."""
    MockSimple = namedtuple("MockSimple", [
        "num_titrant_name", "num_genotype", "log_titrant_conc"
    ])
    data = MockSimple(
        num_titrant_name=1,
        num_genotype=2,
        log_titrant_conc=jnp.array([-np.inf, -np.inf]),
    )
    guesses = get_guesses("th", data)
    assert jnp.allclose(guesses["th_log_hill_K_hyper_loc"], -4.1, atol=1e-5)


def test_get_guesses_offsets_are_zero(mock_data):
    """All per-genotype offsets start at zero."""
    name = "th"
    guesses = get_guesses(name, mock_data)
    for key in [f"{name}_logit_low_offset", f"{name}_logit_delta_offset",
                f"{name}_log_hill_K_offset", f"{name}_log_hill_n_offset"]:
        assert jnp.all(guesses[key] == 0.0), f"{key} should be all zeros"


# ---------------------------------------------------------------------------
# define_model
# ---------------------------------------------------------------------------

def test_define_model_shapes_and_values(mock_data):
    """
    ThetaParam from define_model has per-genotype fields shape (T, G) and
    population moments shape (T, C, 1).
    """
    name = "test_hill"
    priors = get_priors()
    guesses = get_guesses(name, mock_data)

    substituted_model = substitute(define_model, data=guesses)
    theta_param = substituted_model(name=name, data=mock_data, priors=priors)

    T = mock_data.num_titrant_name
    G = mock_data.num_genotype
    C = mock_data.num_titrant_conc

    assert theta_param.theta_low.shape  == (T, G)
    assert theta_param.theta_high.shape == (T, G)
    assert theta_param.log_hill_K.shape == (T, G)
    assert theta_param.hill_n.shape     == (T, G)
    assert theta_param.mu.shape    == (T, C, 1)
    assert theta_param.sigma.shape == (T, C, 1)


# ---------------------------------------------------------------------------
# run_model
# ---------------------------------------------------------------------------

def test_run_model_calculation(mock_data):
    """
    Strict Hill equation check: K=0, n=1 → occupancy = sigmoid(log_conc).
    """
    T, G = mock_data.num_titrant_name, mock_data.num_genotype
    C = 3

    theta_param = ThetaParam(
        theta_low=jnp.zeros((T, G)),
        theta_high=jnp.ones((T, G)),
        log_hill_K=jnp.zeros((T, G)),
        hill_n=jnp.ones((T, G)),
        mu=jnp.zeros((T, C, 1)),
        sigma=jnp.ones((T, C, 1)),
    )

    data = mock_data._replace(log_titrant_conc=jnp.array([-10.0, 0.0, 10.0]),
                               scatter_theta=0)
    result = run_model(theta_param, data)

    assert jnp.allclose(result[:, 0, :], 0.0, atol=1e-3)
    assert jnp.allclose(result[:, 1, :], 0.5)
    assert jnp.allclose(result[:, 2, :], 1.0, atol=1e-3)


def test_run_model_scatter(theta_param_setup, mock_data):
    """scatter_theta=1 inserts four leading singleton dims."""
    result = run_model(theta_param_setup, mock_data._replace(scatter_theta=1))
    T, C, G = (mock_data.num_titrant_name,
               mock_data.num_titrant_conc,
               mock_data.num_genotype)
    assert result.shape == (1, 1, 1, 1, T, C, G)


def test_run_model_no_scatter(theta_param_setup, mock_data):
    """scatter_theta=0 returns (T, C, G_subset)."""
    result = run_model(theta_param_setup, mock_data._replace(scatter_theta=0))
    T, C, G = (mock_data.num_titrant_name,
               mock_data.num_titrant_conc,
               mock_data.num_genotype)
    assert result.shape == (T, C, G)


def test_run_model_batch_idx_translation(mock_data):
    """run_model uses data.batch_idx[geno_theta_idx], not geno_theta_idx directly."""
    T, G = mock_data.num_titrant_name, mock_data.num_genotype
    C = mock_data.num_titrant_conc

    # Distinct theta_low per genotype so we can tell them apart
    theta_low = jnp.arange(T * G, dtype=float).reshape(T, G)
    theta_param = ThetaParam(
        theta_low=theta_low,
        theta_high=jnp.ones((T, G)),
        log_hill_K=jnp.full((T, G), 1e6),    # very high K → occupancy ≈ 0 → theta ≈ theta_low
        hill_n=jnp.ones((T, G)),
        mu=jnp.zeros((T, C, 1)),
        sigma=jnp.ones((T, C, 1)),
    )

    # batch_idx = [2, 0, 1]: batch position 0 → genotype 2, etc.
    batch_idx     = jnp.array([2, 0, 1], dtype=jnp.int32)
    geno_theta_idx = jnp.array([0, 1],   dtype=jnp.int32)  # want batch positions 0, 1

    data = mock_data._replace(batch_idx=batch_idx,
                               geno_theta_idx=geno_theta_idx,
                               scatter_theta=0)
    result = run_model(theta_param, data)

    # batch positions 0 and 1 map to genotypes 2 and 0
    # At very high K, occupancy ≈ 0, so theta ≈ theta_low
    expected_theta_low = theta_low[:, jnp.array([2, 0])]
    assert jnp.allclose(result[:, 0, :], expected_theta_low, atol=1e-4)


# ---------------------------------------------------------------------------
# guide
# ---------------------------------------------------------------------------

def test_guide_logic_and_shapes(mock_data):
    """Guide returns ThetaParam with (T, G) per-genotype fields and (T, C, 1) moments."""
    name = "test_hill_guide"
    priors = get_priors()

    with seed(rng_seed=0):
        theta_param = guide(name=name, data=mock_data, priors=priors)

    T, G, C = (mock_data.num_titrant_name,
               mock_data.num_genotype,
               mock_data.num_titrant_conc)
    assert theta_param.theta_low.shape == (T, G)
    assert theta_param.mu.shape        == (T, C, 1)
    assert theta_param.sigma.shape     == (T, C, 1)


def test_guide_values_in_valid_range(mock_data):
    with seed(rng_seed=42):
        tp = guide(name="test_hill_range", data=mock_data, priors=get_priors())
    assert jnp.all(tp.theta_low  >= 0) and jnp.all(tp.theta_low  <= 1)
    assert jnp.all(tp.theta_high >= 0) and jnp.all(tp.theta_high <= 1)


# ---------------------------------------------------------------------------
# get_population_moments / _population_moments
# ---------------------------------------------------------------------------

def test_population_moments_shape(mock_data):
    """Population moments from define_model are (T, C, 1)."""
    name = "test_moments"
    priors = get_priors()

    with seed(rng_seed=0):
        theta_param = define_model(name, mock_data, priors)

    mu, sigma = get_population_moments(theta_param, mock_data)

    T, C = mock_data.num_titrant_name, mock_data.num_titrant_conc
    assert mu.shape    == (T, C, 1)
    assert sigma.shape == (T, C, 1)
    assert jnp.all(sigma >= 0)


def test_population_moments_helper_shape(mock_data):
    """_population_moments returns (T, C, 1) shapes for the given inputs."""
    T, C = mock_data.num_titrant_name, mock_data.num_titrant_conc

    mu, sigma = _population_moments(
        jnp.full(T, 2.0),  jnp.full(T, 1.0),
        jnp.full(T, -4.0), jnp.full(T, 1.0),
        jnp.full(T, -4.1), jnp.full(T, 0.1),
        jnp.full(T, 0.7),  jnp.full(T, 0.3),
        mock_data.log_titrant_conc,
    )
    assert mu.shape    == (T, C, 1)
    assert sigma.shape == (T, C, 1)
    assert jnp.all(sigma >= 0)


# ---------------------------------------------------------------------------
# predict_unmeasured
# ---------------------------------------------------------------------------

import pandas as pd

from tfscreen.analysis.hierarchical.growth_model.components.theta.hill import (
    predict_unmeasured as hill_predict_unmeasured,
)

_TITRANT_NAMES_H = ["IPTG", "TMAIPP"]
_T_DEFAULT = len(_TITRANT_NAMES_H)


def _make_titrant_df_h():
    return pd.DataFrame({
        "titrant_name": ["IPTG", "IPTG", "IPTG", "TMAIPP", "TMAIPP", "TMAIPP"],
        "titrant_conc": [0.0, 1e-4, 1e-3, 0.0, 1e-4, 1e-3],
    })


def _make_hill_posteriors(S=10, T=_T_DEFAULT, seed=0):
    """
    Fake posteriors for the hill (non-mut) model.

    Hyperprior location parameters have shape (S, T) — one per sample per
    titrant — matching the per-titrant plate structure.
    """
    rng = np.random.default_rng(seed)
    post = {}
    post["theta_logit_low_hyper_loc"]   = rng.standard_normal((S, T)).astype(np.float32) + 2.0
    post["theta_logit_delta_hyper_loc"] = rng.standard_normal((S, T)).astype(np.float32) - 4.0
    post["theta_log_hill_K_hyper_loc"]  = rng.standard_normal((S, T)).astype(np.float32) - 4.1
    post["theta_log_hill_n_hyper_loc"]  = rng.standard_normal((S, T)).astype(np.float32) * 0.3
    return post


class TestHillPredictUnmeasured:

    def _q(self):
        return {"median": 0.5, "lower": 0.025, "upper": 0.975}

    def test_output_shape_and_columns(self):
        post = _make_hill_posteriors()
        result = hill_predict_unmeasured(
            target_genotypes=["wt", "M42I"],
            titrant_names=_TITRANT_NAMES_H,
            manual_titrant_df=_make_titrant_df_h(),
            mut_labels=["M42I", "K84L"],
            pair_labels=[],
            param_posteriors=post,
            q_to_get=self._q(),
        )
        # 2 genotypes × 6 rows in titrant_df
        assert len(result) == 2 * 6
        for col in ["genotype", "titrant_name", "titrant_conc",
                    "median", "lower", "upper"]:
            assert col in result.columns

    def test_theta_in_unit_interval(self):
        post = _make_hill_posteriors()
        result = hill_predict_unmeasured(
            target_genotypes=["wt", "M42I"],
            titrant_names=_TITRANT_NAMES_H,
            manual_titrant_df=_make_titrant_df_h(),
            mut_labels=["M42I"],
            pair_labels=[],
            param_posteriors=post,
            q_to_get={"median": 0.5},
        )
        assert (result["median"] >= 0).all()
        assert (result["median"] <= 1).all()
        assert not result["median"].isna().any()

    def test_unknown_mutations_not_nan(self):
        """hill has no mutation structure; unknown mutations are NOT NaN-masked."""
        post = _make_hill_posteriors(T=1)
        result = hill_predict_unmeasured(
            target_genotypes=["wt", "NOVELXYZ"],
            titrant_names=["IPTG"],
            manual_titrant_df=pd.DataFrame({
                "titrant_name": ["IPTG"],
                "titrant_conc": [1e-4],
            }),
            mut_labels=["M42I"],
            pair_labels=[],
            param_posteriors=post,
            q_to_get={"median": 0.5},
        )
        assert not result["median"].isna().any()

    def test_all_genotypes_get_same_prediction_per_titrant(self):
        """
        Since hill has no per-mutation effects, all genotypes for a given
        titrant receive the same population-mean prediction.
        """
        post = _make_hill_posteriors(S=20, T=1, seed=3)
        titrant_df = pd.DataFrame({
            "titrant_name": ["IPTG"],
            "titrant_conc": [1e-4],
        })
        result = hill_predict_unmeasured(
            target_genotypes=["wt", "M42I", "K84L", "M42I/K84L"],
            titrant_names=["IPTG"],
            manual_titrant_df=titrant_df,
            mut_labels=["M42I", "K84L"],
            pair_labels=[],
            param_posteriors=post,
            q_to_get={"median": 0.5},
        )
        medians = result["median"].values
        np.testing.assert_allclose(medians, medians[0], atol=1e-6)

    def test_zero_conc_handled(self):
        post = _make_hill_posteriors(T=1)
        result = hill_predict_unmeasured(
            target_genotypes=["wt"],
            titrant_names=["IPTG"],
            manual_titrant_df=pd.DataFrame({
                "titrant_name": ["IPTG"],
                "titrant_conc": [0.0],
            }),
            mut_labels=[],
            pair_labels=[],
            param_posteriors=post,
            q_to_get={"median": 0.5},
        )
        assert np.isfinite(result["median"].values).all()

    def test_upper_ge_median_ge_lower(self):
        post = _make_hill_posteriors(S=50, seed=7)
        result = hill_predict_unmeasured(
            target_genotypes=["wt"],
            titrant_names=_TITRANT_NAMES_H,
            manual_titrant_df=_make_titrant_df_h(),
            mut_labels=[],
            pair_labels=[],
            param_posteriors=post,
            q_to_get=self._q(),
        )
        assert (result["upper"] >= result["median"]).all()
        assert (result["median"] >= result["lower"]).all()

    def test_different_titrants_get_different_predictions(self):
        """
        With per-titrant hyperpriors, IPTG and TMAIPP predictions should
        differ when their posterior K values differ.
        """
        S, T = 50, 2
        post = _make_hill_posteriors(S=S, T=T, seed=99)
        # Force a large difference in K between the two titrants
        post["theta_log_hill_K_hyper_loc"][:, 0] = -8.0   # IPTG: very low K
        post["theta_log_hill_K_hyper_loc"][:, 1] =  0.0   # TMAIPP: high K

        titrant_df = pd.DataFrame({
            "titrant_name": ["IPTG", "TMAIPP"],
            "titrant_conc": [1e-4,   1e-4],
        })
        result = hill_predict_unmeasured(
            target_genotypes=["wt"],
            titrant_names=_TITRANT_NAMES_H,
            manual_titrant_df=titrant_df,
            mut_labels=[],
            pair_labels=[],
            param_posteriors=post,
            q_to_get={"median": 0.5},
        )
        iptg_pred   = result.loc[result["titrant_name"] == "IPTG",   "median"].values[0]
        tmaipp_pred = result.loc[result["titrant_name"] == "TMAIPP", "median"].values[0]
        assert abs(iptg_pred - tmaipp_pred) > 0.05
