

# Reading frame 0, 1, 2. no reverse (negative) allowed.
reading_frame: 0

# amino acid residue number for first in-frame residue
first_amplicon_residue: 27

# wildtype sequence (nucleic acids)
wt_seq:
  gccagccacgtttctgcgaaaacgcgggaaaaagtggaagcggcgatggcggagctgaattacattcccaaccgcgtggcacaacaactggcgggcaaacagtcgttgctgattggcgttgccacctccagtctggccctgcacgcgccgtcgcaaattgtcgcggcgattaaatctcgcgccgatcaactgggtgccagcgtggtggtgtcgatg

# degenerate codons defining the library
degen_sites:
  ......nntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnnt......nntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnntnnt

# sub_libraries defines blocks of contiguous library components cloned in 
# together. '.' indicates wildtype sequence; each unique character beside '.'
# defines a unique sub-library. These must be contiguous (...111... is okay, 
# ...11.1... is not)
sub_libraries:
  ......111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111......222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222

# Flanking sequences just upstream and just downstream of the amplicon
expected_5p: cgcgtggtgaaccag
expected_3p: gtagaacgaagcggc

# library_combos should be formatted like 'single-x' or 'double-x-y' where 'x'
# and 'y' are library characters in sub_libraries. 'single-x' specifies all
# individual degenerate codons in x. 'double-x-x' specifies doubles between
# degenerate codons in x. 'double-x-y' specifies doubles between sub-libraries
# x and y but not internal doubles.
library_combos: ["single-1","single-2","double-1-2"]

# These are sequences that are not part of the library that we include as controls
# etc. 
spiked_seqs:
- gccagccacgtttctgcgaaaacgcgggaaaaagtggaagcggcgatggcggagctgaattacattcccaaccgcgtggcacaacaactggcgggcaaacagtcgttgctgattggcgttgccacctccagtctggccctggcggcgccgtcgcaaattgtcgcggcgattctgtctcgcgccgatcaactgggtgccagcgtggtggtgtcgatg
- gccagccacgtttctgcgaaaacgcgggaaaaagtggaagcggcgattgcggagctgaattacattcccaaccgcgtggcacaacaactggcgggcaaacagtcgttgctgattggcgttgccacctccagtctggccctggcggcgccgtcgcaaattgtcgcggcgattctgtctcgcgccgatcaactgggtgccagcgtggtggtgtcgatg
- gccagccacgtttctgcgaaaacgcgggaaaaagtggaagcggcgatggcggagctgaattacattcccaaccgcgtggcacaacaactggcgggcaaacagtcgttgctgattggcgttgccacctccagtctggccctgcacgcgccgtcgcaaattgtcgcggcgattaaatctcgcgccgcccaactgggtgccagcgtggtggtgtcgatg