"""
Write docs/source/cli.rst: the --help of every tfs-* command.

The page is generated from the same parsers the commands build
(``generalized_main``), so the flags it lists are the flags the code takes.
Rerun after changing any CLI signature or docstring:

    python docs/scripts/make_cli_reference.py

``tests/tfscreen/util/cli/test_cli_reference.py`` fails when the page is stale.
"""

import importlib
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "docs", "source", "cli.rst")

HEADER = """\
.. This file is generated by docs/scripts/make_cli_reference.py. Do not edit.

=============
CLI reference
=============

Every ``tfs-*`` command, as its ``--help`` prints it. Arguments without a
leading ``--`` are positional and required. A switch that is on by default is
turned off with ``--no_<name>``. Every command prints its provenance (tfscreen
version, git commit, command line) when it starts and, if it takes
``--out_prefix``, writes it to ``{out_prefix}_provenance.json``.

The commands in pipeline order are described in :doc:`pipeline`.

.. contents::
   :local:
   :depth: 1

"""

# Pipeline order; any command not listed here goes at the end, alphabetically.
ORDER = [
    "tfs-process-fastq",
    "tfs-calibrate-od600",
    "tfs-process-counts",
    "tfs-configure-model",
    "tfs-prefit-calibration",
    "tfs-fit-model",
    "tfs-sample-posterior",
    "tfs-extract-params",
    "tfs-predict-theta",
    "tfs-predict-growth",
    "tfs-predict-epistasis",
    "tfs-extract-epistasis",
    "tfs-cat-response",
    "tfs-compare-runs",
    "tfs-summarize-fit",
    "tfs-fit-genotypes",
    "tfs-sample-prior",
    "tfs-simulate",
    "tfs-build-empirical",
    "tfs-setup-sim-grid",
    "tfs-setup-grid",
    "tfs-summarize-grid",
    "tfs-summarize-calibration",
]


def entry_points():
    with open(os.path.join(ROOT, "pyproject.toml"), "rb") as fh:
        scripts = tomllib.load(fh)["project"]["scripts"]
    names = [n for n in ORDER if n in scripts]
    names += sorted(n for n in scripts if n not in ORDER)
    return [(n, scripts[n]) for n in names]


def help_text(name, target):
    from tfscreen.util.cli.generalized_main import capture_parser
    module, func = target.split(":")
    main = getattr(importlib.import_module(module), func)
    parser = capture_parser(main)
    parser.prog = name
    return parser.format_help()


def render():
    # fixed width so the page does not depend on the terminal
    os.environ["COLUMNS"] = "88"
    parts = [HEADER]
    for name, target in entry_points():
        text = help_text(name, target)
        parts.append(f"{name}\n{'-' * len(name)}\n\n.. code-block:: text\n\n")
        parts.append("".join(f"   {line}".rstrip() + "\n"
                             for line in text.splitlines()))
        parts.append("\n")
    return "".join(parts).rstrip() + "\n"


def main():
    text = render()
    check = "--check" in sys.argv
    if check:
        with open(OUT) as fh:
            if fh.read() != text:
                sys.exit("docs/source/cli.rst is stale; run "
                         "python docs/scripts/make_cli_reference.py")
        return
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
