"""
Set up a directory grid for pre-fit calibration model comparison.

Creates one subdirectory per (condition_growth, growth_transition, theta_rescale)
combination so that ``tfs-prefit-calibration`` can be run independently in each,
then summarised with ``tfs-summarize-grid-calibration``.

Each subdirectory contains:

- ``run_config.yaml`` — component-specific configuration generated by
  ``write_configuration``, with ``priors_file`` / ``guesses_file`` pointing to
  local copies generated for that component combination.
- ``run_priors.csv``, ``run_guesses.csv`` — parameter priors and initial guesses
  appropriate for the specific component combination.

A sequential ``run_all.sh`` script is written to the grid root directory.
"""

import itertools
import os
import stat

import yaml

from tfscreen.util.cli import generalized_main, read_lines
from tfscreen.analysis.hierarchical.growth_model.registry import model_registry
from tfscreen.analysis.hierarchical.growth_model.model_class import ModelClass as GrowthModel
from tfscreen.analysis.hierarchical.growth_model.configuration_io import write_configuration
from tfscreen.analysis.hierarchical.growth_model.scripts.configure_model_cli import (
    INCOMPATIBLE_CG_TR,
)

# Separator used between component names in subdirectory names.
_SEP = "__"

# The three axes that are varied across the grid.
_GRID_AXES = ("condition_growth", "growth_transition", "theta_rescale")

# Alias so the test suite can import _INCOMPATIBLE_CG_TR from this module.
# The canonical definition and rationale live in configure_model_cli.py.
_INCOMPATIBLE_CG_TR = INCOMPATIBLE_CG_TR

# Fixed out_prefix used inside every per-combination run.
_RUN_OUT_PREFIX = "prefit"

# Name stem used for per-combination config/priors/guesses files.
_CONFIG_STEM = "run"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_axis_values(axis, file_path):
    """Return the list of component names to use for *axis*.

    If *file_path* is provided, read values from that file (one per line, ``#``
    comments ignored).  Otherwise return all keys registered for the axis.
    Unknown names raise ``ValueError``.
    """
    registered = set(model_registry[axis].keys())
    if file_path is not None:
        values = read_lines(file_path)
        unknown = sorted(set(values) - registered)
        if unknown:
            raise ValueError(
                f"Unknown {axis} value(s): {unknown}. "
                f"Registered: {sorted(registered)}"
            )
        return values
    return sorted(registered)


def _subdir_name(cg, gt, tr):
    return f"{cg}{_SEP}{gt}{_SEP}{tr}"


def _resolve_path(raw, base_dir):
    """Return absolute path, resolving *raw* relative to *base_dir*."""
    if os.path.isabs(raw):
        return raw
    return os.path.normpath(os.path.join(base_dir, raw))


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def setup_grid_calibration(config_file,
                           out_prefix="grid_calibration",
                           condition_growth_file=None,
                           growth_transition_file=None,
                           theta_rescale_file=None,
                           seed=0,
                           prefit_args=None):
    """
    Set up a pre-fit calibration grid directory.

    Creates one subdirectory per (condition_growth, growth_transition,
    theta_rescale) combination.  Each subdirectory contains a
    ``run_config.yaml`` and component-specific ``run_priors.csv`` /
    ``run_guesses.csv`` generated by building a :class:`GrowthModel` for that
    combination and calling :func:`write_configuration`.  A ``run_all.sh``
    script is written to *out_prefix* to run all calibrations sequentially.

    Parameters
    ----------
    config_file : str
        Path to a production YAML configuration file used as the base for all
        grid runs.  Must contain a ``data`` section with ``growth`` and
        ``binding`` paths and a ``components`` section with the non-grid
        component settings.
    out_prefix : str, optional
        Directory that will hold all per-combination subdirectories and the
        ``run_all.sh`` script.  Created if it does not already exist.
        Default ``"grid_calibration"``.
    condition_growth_file : str or None, optional
        Path to a text file listing the ``condition_growth`` component names to
        include (one per line, ``#`` comments allowed).  When ``None`` all
        registered components are used.
    growth_transition_file : str or None, optional
        Path to a text file listing the ``growth_transition`` component names.
        When ``None`` all registered components are used.
    theta_rescale_file : str or None, optional
        Path to a text file listing the ``theta_rescale`` component names.
        When ``None`` all registered components are used.
    seed : int, optional
        Random seed forwarded to ``tfs-prefit-calibration`` in ``run_all.sh``.
        Default ``0``.
    prefit_args : str or None, optional
        Extra arguments appended verbatim to every ``tfs-prefit-calibration``
        call in ``run_all.sh``.  Use this to pass any flag accepted by
        ``tfs-prefit-calibration`` without having to re-run setup, e.g.
        ``"--convergence_tolerance 0.001 --max_num_epochs 50000"``.
        Default ``None`` (no extra arguments).

    Returns
    -------
    list of tuple
        Sorted list of ``(condition_growth, growth_transition, theta_rescale)``
        triples that were created.
    """
    config_file = os.path.abspath(config_file)
    if not os.path.exists(config_file):
        raise FileNotFoundError(f"Config file not found: {config_file}")

    with open(config_file) as fh:
        base_cfg = yaml.safe_load(fh)

    cfg_dir = os.path.dirname(config_file)

    # Resolve data paths from the base config.
    if "data" not in base_cfg:
        raise ValueError(f"'data' section missing in {config_file}")
    data = base_cfg["data"]
    growth_path = _resolve_path(data["growth"], cfg_dir)
    binding_path = _resolve_path(data["binding"], cfg_dir)

    # Extract non-grid component settings from the base config.
    base_components = dict(base_cfg.get("components", {}))
    batch_size = base_components.pop("batch_size", None)
    for axis in _GRID_AXES:
        base_components.pop(axis, None)

    # Determine grid axes.
    cg_values = _get_axis_values("condition_growth", condition_growth_file)
    gt_values = _get_axis_values("growth_transition", growth_transition_file)
    tr_values = _get_axis_values("theta_rescale", theta_rescale_file)

    # Create grid root directory.
    os.makedirs(out_prefix, exist_ok=True)

    all_combos = list(itertools.product(cg_values, gt_values, tr_values))

    # Filter out known incompatible combinations before building any models.
    combos = []
    skipped = []
    for cg, gt, tr in all_combos:
        if (cg, tr) in _INCOMPATIBLE_CG_TR:
            skipped.append((cg, gt, tr))
        else:
            combos.append((cg, gt, tr))

    if skipped:
        print(
            f"Skipping {len(skipped)} incompatible combination(s) "
            f"(condition_growth × theta_rescale mismatch):",
            flush=True,
        )
        for cg, gt, tr in skipped:
            print(f"  {_subdir_name(cg, gt, tr)}", flush=True)

    subdir_names = []

    for cg, gt, tr in combos:
        name = _subdir_name(cg, gt, tr)
        subdir = os.path.join(out_prefix, name)
        os.makedirs(subdir, exist_ok=True)

        # Build a GrowthModel for this specific component combination so that
        # write_configuration generates the correct priors and guesses.
        gm = GrowthModel(growth_path, binding_path,
                         batch_size=batch_size,
                         condition_growth=cg,
                         growth_transition=gt,
                         theta_rescale=tr,
                         **base_components)

        # Write run_config.yaml, run_priors.csv, run_guesses.csv into subdir.
        write_configuration(gm,
                            out_prefix=os.path.join(subdir, _CONFIG_STEM),
                            growth_df_path=growth_path,
                            binding_df_path=binding_path)

        subdir_names.append(name)

    # Write run_all.sh
    lines = [
        "#!/bin/bash",
        "set -e",
        "# Generated by tfs-setup-grid-calibration",
        f"# Grid: {len(combos)} combination(s)",
        "",
        '# Always run from the directory that contains this script.',
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'cd "$SCRIPT_DIR"',
        "",
    ]
    extra = f" {prefit_args.strip()}" if prefit_args and prefit_args.strip() else ""
    for name in subdir_names:
        lines.append(f'echo "Running {name} ..."')
        lines.append(
            f'(cd "{name}" && tfs-prefit-calibration {_CONFIG_STEM}_config.yaml'
            f" --seed {seed} --out_prefix {_RUN_OUT_PREFIX}{extra})"
        )
    lines.append("")
    lines.append('echo "All calibrations complete."')

    sh_path = os.path.join(out_prefix, "run_all.sh")
    with open(sh_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    # Make executable.
    current = os.stat(sh_path).st_mode
    os.chmod(sh_path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    n = len(combos)
    print(
        f"Created {n} calibration director{'y' if n == 1 else 'ies'} under {out_prefix}/",
        flush=True,
    )
    print(f"Run with: bash {sh_path}", flush=True)

    return combos


def main():
    generalized_main(
        setup_grid_calibration,
        manual_arg_types={
            "config_file": str,
            "condition_growth_file": str,
            "growth_transition_file": str,
            "theta_rescale_file": str,
            "seed": int,
            "prefit_args": str,
        },
    )


if __name__ == "__main__":
    main()
